# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss/sensor/io
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_laser_led.o
