ccflags-y += -I$(srctree)/drivers/media/video/msm
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/pproc/cpp
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/msm_buf_mgr/

obj-$(CONFIG_MSM_FD) += msm_fd_dev.o msm_fd_hw.o
