ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
