# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss/msm_vb2
obj-$(CONFIG_MSMB_CAMERA) += camera.o
