ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
