# SPDX-License-Identifier: GPL-2.0-only
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-oss/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_csid.o
