ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/sensor
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/sensor/cci
ccflags-y += -I$(srctree)/drivers/misc/
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o msm_camera_tz_i2c.o
