ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/isp/
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/common
ccflags-y += -I$(srctree)/drivers/media/platform/msm/camera_v2-legacy/msm_buf_mgr/
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
